#for cnn model
confidence:
  threshold: 0.50

vision:
  checkpoint_path: "models/vision_model.pth"
  image_size: 224
  class_names: ["AD", "NORMAL"]
  device: "cpu"

#for faiss
retrieval:
  # Number of top-k documents 
  top_k: 2
  db_path: "faiss_index"
  # we use huggingFace sentence-transformer model used for embedding.
  embedding_model: "all-MiniLM-L6-v2"
# euclidean distance in our vector db
  relevance_distance_threshold: 1.3


llm:
  gemini:
    active: true
    model: "gemini-2.0-flash"
    temperature: 0.0
  groq:
    active: false
    model: "llama-3.3-70b-versatile"
    temperature: 0.0
  openai:
    active: false
    model: "gpt-4o-mini"
    temperature: 0.0
